name: Send a telegram message when new Youtube videos update
on:
  youtube:
    channel_id:
      - UCnmF6Fy8t1aIDl5jlLqSAqw
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: MAGIC STRAWBERRY SOUND
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR }}
        uses: Ilshidur/action-discord@master
        with:
          args: "`${{on.youtube.outputs.author}} - YouTube`'\n'**${{on.youtube.outputs.title}}**'\n'${{on.youtube.outputs.link}}"
